at new Promise (<anonymous>)
    at promiseOrCallback (/home/container/node_modules/[4mmongoose[24m/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/home/container/node_modules/[4mmongoose[24m/lib/index.js:1149:10)
    at Mongoose.connect (/home/container/node_modules/[4mmongoose[24m/lib/index.js:350:20)
    at module.exports (/home/container/mongo.js:7:18)
    at Client.<anonymous> (/home/container/index.js:33:9)
[90m    at Client.emit (node:events:527:28)[39m
    at WebSocketManager.triggerClientReady (/home/container/node_modules/[4mdiscord.js[24m/src/client/websocket/WebSocketManager.js:379:17)
    at WebSocketManager.checkShardsReady (/home/container/node_modules/[4mdiscord.js[24m/src/client/websocket/WebSocketManager.js:362:10)
    at WebSocketShard.<anonymous> (/home/container/node_modules/[4mdiscord.js[24m/src/client/websocket/WebSocketManager.js:189:14)
[90m    at WebSocketShard.emit (node:events:527:28)[39m
    at WebSocketShard.checkReady (/home/container/node_modules/[4mdiscord.js[24m/src/client/websocket/WebSocketShard.js:524:12)
    at WebSocketShard.onPacket (/home/container/node_modules/[4mdiscord.js[24m/src/client/websocket/WebSocketShard.js:496:16) {
  reason: TopologyDescription {
    type: [32m'ReplicaSetNoPrimary'[39m,
    setName: [1mnull[22m,
    maxSetVersion: [1mnull[22m,
    maxElectionId: [1mnull[22m,
    servers: Map(3) {
      [32m'cluster0-shard-00-00.v9q60.mongodb.net:27017'[39m => ServerDescription {
        address: [32m'cluster0-shard-00-00.v9q60.mongodb.net:27017'[39m,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/home/container/node_modules/[4mmongoose[24m/node_modules/[4mmongodb[24m/lib/core/connection/connect.js:362:14)
            at TLSSocket.<anonymous> (/home/container/node_modules/[4mmongoose[24m/node_modules/[4mmongodb[24m/lib/core/connection/connect.js:330:16)
        [90m    at Object.onceWrapper (node:events:641:28)[39m
        [90m    at TLSSocket.emit (node:events:527:28)[39m
        [90m    at TLSSocket.Socket._onTimeout (node:net:522:8)[39m
        [90m    at listOnTimeout (node:internal/timers:559:17)[39m
        [90m    at processTimers (node:internal/timers:502:7)[39m,
        roundTripTime: [33m-1[39m,
        lastUpdateTime: [33m12826446[39m,
        lastWriteDate: [1mnull[22m,
        opTime: [1mnull[22m,
        type: [32m'Unknown'[39m,
        topologyVersion: [90mundefined[39m,
        minWireVersion: [33m0[39m,
        maxWireVersion: [33m0[39m,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      },
      [32m'cluster0-shard-00-01.v9q60.mongodb.net:27017'[39m => ServerDescription {
        address: [32m'cluster0-shard-00-01.v9q60.mongodb.net:27017'[39m,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/home/container/node_modules/[4mmongoose[24m/node_modules/[4mmongodb[24m/lib/core/connection/connect.js:362:14)
            at TLSSocket.<anonymous> (/home/container/node_modules/[4mmongoose[24m/node_modules/[4mmongodb[24m/lib/core/connection/connect.js:330:16)
        [90m    at Object.onceWrapper (node:events:641:28)[39m
        [90m    at TLSSocket.emit (node:events:527:28)[39m
        [90m    at TLSSocket.Socket._onTimeout (node:net:522:8)[39m
        [90m    at listOnTimeout (node:internal/timers:559:17)[39m
        [90m    at processTimers (node:internal/timers:502:7)[39m,
        roundTripTime: [33m-1[39m,
        lastUpdateTime: [33m12826447[39m,
        lastWriteDate: [1mnull[22m,
        opTime: [1mnull[22m,
        type: [32m'Unknown'[39m,
        topologyVersion: [90mundefined[39m,
        minWireVersion: [33m0[39m,
        maxWireVersion: [33m0[39m,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      },
      [32m'cluster0-shard-00-02.v9q60.mongodb.net:27017'[39m => ServerDescription {
        address: [32m'cluster0-shard-00-02.v9q60.mongodb.net:27017'[39m,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/home/container/node_modules/[4mmongoose[24m/node_modules/[4mmongodb[24m/lib/core/connection/connect.js:362:14)
            at TLSSocket.<anonymous> (/home/container/node_modules/[4mmongoose[24m/node_modules/[4mmongodb[24m/lib/core/connection/connect.js:330:16)
        [90m    at Object.onceWrapper (node:events:641:28)[39m
        [90m    at TLSSocket.emit (node:events:527:28)[39m
        [90m    at TLSSocket.Socket._onTimeout (node:net:522:8)[39m
        [90m    at listOnTimeout (node:internal/timers:559:17)[39m
        [90m    at processTimers (node:internal/timers:502:7)[39m,
        roundTripTime: [33m-1[39m,
        lastUpdateTime: [33m12826524[39m,
        lastWriteDate: [1mnull[22m,
        opTime: [1mnull[22m,
        type: [32m'Unknown'[39m,
        topologyVersion: [90mundefined[39m,
        minWireVersion: [33m0[39m,
        maxWireVersion: [33m0[39m,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: [33mfalse[39m,
    compatible: [33mtrue[39m,
    compatibilityError: [1mnull[22m,
    logicalSessionTimeoutMinutes: [1mnull[22m,
    heartbeatFrequencyMS: [33m10000[39m,
    localThresholdMS: [33m15[39m,
    commonWireVersion: [1mnull[22m
  }
}

Node.js v17.9.1